name: 'Basecone - Create a Release Tag'
description: 'Create a Release Tag'
inputs:
  tag:
    description: 'The name of the tag to create'
    required: true

# outputs:
#   tag_exists:
#     description: "The tag already existed."
# runs:
#   using: "docker"
#   image: "Dockerfile"
# branding:
#   icon: "tag"
#   color: "blue"

runs:
  using: "composite"
  steps:
  - id: createsrelease
    run: |
      echo "Hello World Create a Release Tag: ${{ inputs.tag }} "
    shell: bash

  - name: Checkout
    uses: actions/checkout@v2
    with:
        fetch-depth: '0'

  - name: Install GitVersion
    uses: gittools/actions/gitversion/setup@v0.9.7
    with:
        versionSpec: '5.x'

  - name: Determine Version
    uses: gittools/actions/gitversion/execute@v0.9.7
  
  - name: Create Tag
    shell: bash
    run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a v2.1 -m v2.1-release
        git push origin v2.1
      
