name: 'Basecone - Create a Release Tag'
description: 'Create a Release Tag'
inputs:
  tag: 
    description: 'The name of the tag to create'
    required: true
runs:
  using: "composite"
  steps:
    - id: createsbudget
      run: |
        echo "Hello World Create a Release Tag: ${{ inputs.tag }} "
      shell: bash
