name: Testing

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Echo
        run: echo "Hello World Create a Release Tag"

      - name: Create a Release Tag
        uses: vishalpatel-73/create-a-release-tag-test@v1.1
        with:
          tag: "Test Tag"

      # - uses: ./actions/create_release_tag.yml
      #   id: "tag_create"
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: "1.0"
        #   message: "Test"
        #   tag_exists_error: "No Error"
