name: Testing

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Echo
        run: echo "Hello World Create a Release Tag"

      - name: Create a Release Tag
        uses: vishalpatel-73/create-a-release-tag-test@v1.1
        with:
          tag: "v1.0.${{ secrets.GITHUB_TOKEN }}-prerelease"
